### ISSUE TITLE
App freezing on chara making

### ISSUE THREAD

**Issue by Tomon613** [ElonaFoobar/ElonaFoobar#183] opened 2018-04-27 23:17 UTC
In chara making, after 3 feet selected, app gets freezed. How can I fix it?

# Environment

* OS version: OSX El Capitan
* Elona Foobar verision: latest (2018.4.28)

**Comment by ki-foobar** [comment] 2018-04-28 07:36
I cannot reproduce this issue so far. You mean that app freezed between feats menu and alias roll menu, right?
Can you tell me your selected race/class/feats please?

**Comment by tamanugi** [comment] 2018-04-30 06:07
I got it where the problem occurred.

https://github.com/ElonaFoobar/ElonaFoobar/blob/develop/text.cpp#L2709-L2718
It seems that an infinite loop is occurring here

**Comment by tamanugi** [comment] 2018-05-04 14:05
@Tomon613 
I also freezes at the same, but the cause was reading map data.
I copied `elona/map` from original elona and it work well.

**Comment by ki-foobar** [comment] 2018-05-05 00:10
I have fortotten to say about data files.

Foobar's data files in map/ or data/ directories, are NOT compatible with vanilla's.

All binary files compressed by gzip have been decompressed, and all text data encoded cp932(Shift-JIS) have been converted to UTF-8(without BOM).

These data files has not been included in this repository now and you can download them only from the development channel in Elona Discord JP server. Distribution zip is created for Windows, but the data part is the same.

Please download it and replace only the executable file in runtime/ directory.

I apologize that the announcement was delayed.

**Comment by Tomon613** [comment] 2018-05-07 10:35
Built on the latest source (2018.5.7), launching is failed....

**Comment by Tomon613** [comment] 2018-05-07 10:38
Built on the latest cord (2018.5.7), launching is failed with no logs....

**Comment by Ruin0x11** [comment] 2018-05-10 18:53
This should have been fixed in #258.

**Closed** 2018-05-23 00:53 UTC
Labels: bug
