### ISSUE TITLE
Key bind error?

### ISSUE THREAD

**Issue by Tomon613** [ElonaFoobar/ElonaFoobar#141] opened 2018-04-16 03:52 UTC
最新のコードをビルドし起動しましたが、以下のエラーが表示され起動しません。
おそらくキーの設定が変わったのでしょうが...どのように設定すればよいでしょうか？

```
hoge:bin hoge$ ./ElonaFoobar
libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: map::at:  key not found
Abort trap: 6
hoge:bin hoge$
```

Launching failed with above error, maybe caused by wrong key binds. How can i fix it?

# Environment

* OS version: OSX El Capitan (MacBookPro early 2015)
* Elona Foobar verision: latest (2018.4.16)

**Comment by ElonaFoobar** [comment] 2018-04-16 04:24
Maybe this error occurred due to #125. "key_autodig" is newly added at this pull request. Since this commit, `RADME.md` has updated. Please copy&paste `config.json` from `README.md`.
Default value of "key_autodig" is "H" like oom.

`config.json` should be included in this repository. I'll post a new issue about this.

**Comment by ki-foobar** [comment] 2018-04-16 22:35
Hmm... `std::map` is only used by `thirdparty/picojson/picojson.h`, so this error probably occurs in loading configuration file. If you updated `config.json` and cannot resolve the error, I do not know the cause of that. Anyway, I have to implement more kindful error message sooner or later.

**Comment by Tomon613** [comment] 2018-04-25 10:27
On the latest source, app launched well. Thank you.

**Comment by ki-foobar** [comment] 2018-04-30 12:13
I closed this issue because maybe the problem was solved.

**Closed by ki-foobar** 2018-04-30 12:13 UTC
Labels: bug
